version: '3.8'

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"       # Optional: DHCP
      - "80:80/tcp"
      - "443:443/tcp"
      - "3000:3000/tcp"
    environment:
      - TZ=America/Chicago
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    networks:
      - adguard-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiYTY0ZmU2OTZkYzZkYTY3Y2IxYjgyN2EzZmMxOTVjMzgiLCJ0IjoiMDE1NWI1ZWYtMzhiNy00YmRiLTg5YWUtOGE3ZmQ1NzhkYjJmIiwicyI6Ik5UWXdOak5qTUdRdE9EQXlZaTAwTTJGa0xUazVabUV0WXpjMFlUa3hZVFU0WldOaCJ9
    networks:
      - adguard-net

networks:
  adguard-net:
    external: true
